### PR TITLE
Feat: added gpl-3.0-only and gpl-3.0-or-later

### PR DESCRIPTION
**Pull request by MattByName**
#### What type of PR is this?

feat: A new feature
#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) More detail description for this PR.

I've added the two version of the GPLv3: gpl-3.0-only and gpl-3.0-or-later

### CODE REVIEW

**Comment by MattByName** [comment]
Hi this is a great tool, it was just missing GPL3 which I needed as I have files of different languages so the template option didn't suit.

**Comment by justlorain** [comment]
> Hi this is a great tool, it was just missing GPL3 which I needed as I have files of different languages so the template option didn't suit.

Sorry for the late reply. Thank you so much for your PR! 
I made some minor adjustments to the template format to make them more consistent. If possible, could you please check if everything looks good? 
If there are no issues, we can merge this :)

**Comment by MattByName** [comment]
Thanks! I'll take a look and get back to you.

**Comment by justlorain** [comment]
> Thanks! I'll take a look and get back to you.

Hi, any feedback? I'm planning to draft a new release, it would be nice if we could include this PR.

**Comment by MattByName** [comment]
Hi sorry for the delay and thanks for the reminder. The changes are fine for me, thanks for implementing it 🙂

**Pull request merged**
